In [1]:
import os
import numpy as np
import cv2
import os
import open3d as o3d
import json
import glob
from tqdm import tqdm
from natsort import natsorted
# import utils
import copy
import time


from scipy.spatial import ConvexHull

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [ ]:
def clean_pcd(pcd: o3d.geometry.PointCloud, nb_neighbors=10, std_ratio=0.4):
    pcd, _ = pcd.remove_statistical_outlier(nb_neighbors=10, std_ratio=0.4)
    pcd, _ = pcd.remove_radius_outlier(nb_points=20, radius=3)
    return pcd

In [42]:
def custom_draw_geometry_with_rotation(pcd):

    def rotate_view(vis):
        ctr = vis.get_view_control()
        ctr.rotate(3, 0, -2.5, 0)
        return False

    o3d.visualization.draw_geometries_with_animation_callback([pcd],
                                                              rotate_view)
# todo: Input pcd path, to be changed for different pointcloud
# pcd_path = "/home/medicago/Pictures/clean_sample.ply"
# pcd = o3d.io.read_point_cloud(pcd_path)
# custom_draw_geometry_with_rotation(pcd)
pcd = o3d.io.read_point_cloud(pcd_path)
pcd_path = "./data/Batch12_27DAS/plant11.ply"
# pcd_path1 = "/home/sp-medicago/MEDICAGO_data/All_scan/Batch14/20220802/20220802124234/merge/merge_pcd_cam1.ply"
pcd, _ = pcd.remove_statistical_outlier(nb_neighbors=14, std_ratio=0.8) #seems better
pcd, _ = pcd.remove_radius_outlier(nb_points=20, radius=10)

custom_draw_geometry_with_rotation(pcd)

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 


In [44]:
hull, _ = pcd.compute_convex_hull()
print(hull)
print(np.asarray(hull.vertices))
print(np.asarray(hull.triangles))
hull_ls = o3d.geometry.LineSet.create_from_triangle_mesh(hull)
hull_ls.paint_uniform_color((1, 0, 0))
o3d.visualization.draw_geometries([pcd, hull_ls])

TriangleMesh with 339 points and 674 triangles.
[[ 1.93230698e+02 -9.88118438e+01  5.67527510e+02]
 [ 1.68544216e+02  1.57031820e+01  5.92919585e+02]
 [ 1.69014656e+02 -4.99770341e+00  5.94028764e+02]
 ...
 [ 1.14014276e+02  4.25039901e+01  5.46114748e+02]
 [ 1.14159553e+02  4.24554238e+01  5.46153704e+02]
 [ 1.44774564e+02  6.41150893e-02  5.36656294e+02]]
[[  0   1   2]
 [  1   0   3]
 [  4   0   5]
 ...
 [290 191  35]
 [249 307 269]
 [283 307 249]]


In [6]:
pcd_path = "./data/Batch12_27DAS/plant11.ply"
pcd = o3d.io.read_point_cloud(pcd_path)
hull, _ = pcd.compute_convex_hull()
hull_ls = o3d.geometry.LineSet.create_from_triangle_mesh(hull)
hull_ls.paint_uniform_color((1, 0, 0))

points = np.asarray(hull.vertices)
volume = ConvexHull(points).volume
area = ConvexHull(points).area
print(f'Volume is : {volume}')
print(f'Area is : {area}')

# Scipy and open3d have the same process of creating convex hull resulting in exactly same answer
# points = np.asarray(pcd.points)
# volume = ConvexHull(points).volume
# area = ConvexHull(points).area
# print(f'Volume is : {volume}')
# print(f'Area is : {area}')

o3d.visualization.draw_geometries([pcd, hull_ls])

Volume is : 5462453.682553688
Area is : 168873.7922090664
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 


In [7]:
pcd_path = "./data/Batch12_27DAS/plant1.ply"
pcd = o3d.io.read_point_cloud(pcd_path)
hull, _ = pcd.compute_convex_hull()
hull_ls = o3d.geometry.LineSet.create_from_triangle_mesh(hull)
hull_ls.paint_uniform_color((1, 0, 0))

points = np.asarray(hull.vertices)
volume = ConvexHull(points).volume
area = ConvexHull(points).area
print(f'Volume is : {volume}')
print(f'Area is : {area}')
# Scipy and open3d have the same process of creating convex hull resulting in exactly same answer
# points = np.asarray(pcd.points)
# volume = ConvexHull(points).volume
# area = ConvexHull(points).area
# print(f'Volume is : {volume}')
# print(f'Area is : {area}')
o3d.visualization.draw_geometries([pcd, hull_ls])

Volume is : 2955198.006496637
Area is : 110963.0943322191
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
